abc_project/abc_project/urls.py
from django.contrib import admin
from django.urls import path, include
from abc_project import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("limousineapp.urls"))
]
if settings.DEBUG:
    urlpatterns+=static(settings.STATIC_URL,
                        document_root=settings.STATIC_ROOT)
    urlpatterns+=static(settings.MEDIA_URL,
                        document_root=settings.MEDIA_ROOT)

abc_project/limousineapp/urls.py
from . import views
from django.urls import path

app_name = 'limousineapp'

urlpatterns = [
    path('', views.home, name='home'),
    path('index/', views.index, name='index'),
    path('about/',views.about,name='about'),
    path('bahrain/',views.bahrain,name='bahrain'),
    path('saudi/',views.saudi,name='saudi'),
    path('gallery/',views.gallery,name='gallery'),
    path('review/',views.review,name='review'),
    path('contact/',views.contact,name='contact'),
]

abc_project/limousineapp/models.py
from django.db import models

# Create your models here.

abc_project/limousineapp/views.py
from django.shortcuts import render


# Create your views here.

def home(request):
    return render(request, 'home.html')


def index(request):
    return render(request, 'index.html')


def about(request):
    return render(request, 'about.html')


def bahrain(request):
    return render(request, 'bahrain.html')


def saudi(request):
    return render(request, 'saudi.html')


def gallery(request):
    return render(request, 'gallery.html')


def review(request):
    return render(request, 'review.html')


def contact(request):
    return render(request, 'contact.html')

abc_project/templates/about.html
{% extends 'base.html' %}
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
{% block title %}
About Us
{% endblock %}
</head>
{% block content %}
<body>
<div id="about-us" class="container-fluid fh5co-about-us pl-0 py-5 pr-0 parallax-window" data-parallax="scroll" data-image-src="{% static 'images/car2.jpeg' %}">
  <div class="container">
    <div class="col-sm-6 offset-sm-6 py-5">
      <h2 class="wow bounceInLeft" data-wow-delay=".25s">ABOUT US</h2>
      <hr/>
        <h3 class="wow bounceInUp">Best Taxi Services In Bahrain</h3>
        <p class="wow bounceInRight" data-wow-delay=".25s">Being one of the best taxi services in Bahrain, Limo Bahrain provides you with various transportation services in and out of Bahrain. Our services include city travel, hospital emergencies, wedding ceremony travel, luggage transportation, tour and trips in Bahrain and more. Apart from Bahrain travel services, we also provide airport transport services, for travelling to and from Saudi Arabia, Dammam, Riyadh, Al-Khober, Jubail City and Ras Tanoura. </p>

    </div>
    <div class=" col-md-6 border-primary text-center">
      <h4 class="mb-3">Do you require a taxi for your airport travel?</h4>
      <h4 class="mb-3">Are you having a hospital emergency in Bahrain?</h4>

    </div>
    <div class="col-md-6 border-primary text-center">
      <h4 class="mb-3">Are you in need of local taxi services in Bahrain?</h4>
      <h4 class="mb-3">Are you in a hurry for attending your corporate meeting?</h4>
    </div>
    <h3 class="text-center">ABC Limousine guarantees the best travel you have ever made.</h3>
  </div>
</div>
<div class="row">
  <div class="container">

    <h2>Chauffeur Service</h2>
    <p>Are you looking for the best chauffeur services in Bahrain? Limo Bahrain makes it easy for you to book chauffeurs at affordable rates. You can easily book chauffeur though WhatsApp or email and get your trip within minutes. We also provide shuttle services within the Kingdom of Bahrain, helping out organizations for both corporate and private transportation services. Our chauffeurs are well trained so as to make your travel easy, safe and prompt. </p>
<!--    <div>-->
    <video autoplay loop muted>
      <source src="{% static 'images/video2.mp4' %}" type="mp4/video">
    </video>
<!--      </div>-->
  </div>
</div>
</body>
{% endblock %}
</html>

abc_project/templates/bahrain.html
{% extends 'base.html' %}
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    {% block title %}
    Bahrain Rates
    {% endblock %}
</head>

{% block content %}
<body>


<div class="row py-5 mt-5">
    <div class="container">
        <h2 class="text-right">Bahrain Limousine Rates</h2>
        <p>Searching for Bahrain to KSA taxi services? Check out our cheapest trip rates and enjoy affordable limousine service in Bahrain. We provide you with all required facilities to ensure your comfort and pleasure despite of whether you are a resident traveller or distant customer. You can also choose your preferred vehicle from our fleet as per your convenience and comfort.</p>
<!--        <img src="{% static 'images/img2.jpeg' %}" style="width:100px height:50px">-->

        <div class="has_serial_number">
						<div class="row justify-content-lg-between">
							<div class="col-lg-3 col-md-4 col-sm-12 col-xs-12">
								<div class="serial_number text-right aos-init aos-animate" data-aos="fade-up" data-aos-delay="100">
                                    <img src="{% static 'images/img2.jpeg' %}">
									<h4 class="mb-0"> </h4>
								</div>
							</div>


							<!-- Page Content -->
							<div class="page-heading header-text">
								<div class="container">
									<div class="row">

									</div>
								</div>
							</div>

							<div class="more-info about-info" style="margin-top:50px;">
								<div class="container">
									<div class="row">
								<div class="col-md-12">
											<div class="section-heading" style="border:opx solid black;margin-bottom:50px;text-align:left;">
												<h2>Transfer Rates within Bahrain</h2>
												<span>Enjoy your travel</span>
											</div>
										</div>

										<div class="col-md-4 box" style="background-color:rgba(146,146,146,0.10);">
											<div class="more-info-content">
												<div class="row">
													<div class="col-md-12 align-self-center" style="border:0px solid silver;padding:25px;">
														<div class="right-content">
															<span>Transfer Rates within Bahrain</span>
															<h4 style="color:silver;">Transfer from/to the Airport to/from  <em><strong>Zone 1</strong></em></h4>
											<hr>
											<h5 style="color:gray;">Executive Sedan</h5>
											<h6><strong>28.00 BD</strong></h6>
											<br>
											<h5 style="color:gray;">SUV</h5>
											<h6><strong>17.00 BD</strong></h6>
											<br>
											<h5 style="color:gray;">Standard Sedan</h5>
											<h6><strong>15.00 BD</strong></h6>
														</div>
										<hr>
										<span style="color:rgba(0,125,160,1.00);">Covers Manama, Diplomatic Area, Muharraq, Busiateen, Hidd, Galali, Diyar Al Muharraq, Amwaj	</span>
													</div>
												</div>
											</div>
										</div>


								<div class="col-md-4 box" style="background-color:rgba(146,146,146,0.20);">
											<div class="more-info-content">
												<div class="row">
													<div class="col-md-12 align-self-center" style="border:0px solid silver;padding:25px;">
														<div class="right-content">
															<span>Transfer Rates within Bahrain</span>
															<h4 style="color:silver;">Transfer from/to the Airport to/from  <em><strong>Zone 2</strong></em></h4>
											<hr>
											<h5 style="color:gray;">Executive Sedan</h5>
											<h6><strong>32.00 BD</strong></h6>
											<br>
											<h5 style="color:gray;">SUV</h5>
											<h6><strong>20.00 BD</strong></h6>
											<br>
											<h5 style="color:gray;">Standard Sedan</h5>
											<h6><strong>17.00 BD</strong></h6>
														</div>
										<hr>
										<span style="color:rgba(0,125,160,1.00);">Covers Sitra, Isa Town, Sanad, Aali, Riffa, Janabiya	</span>
													</div>
												</div>
											</div>
										</div>


								<div class="col-md-4 box" style="background-color:rgba(146,146,146,0.10);">
											<div class="more-info-content">
												<div class="row">
													<div class="col-md-12 align-self-center" style="border:0px solid silver;padding:25px;">
														<div class="right-content">
															<span>Transfer Rates within Bahrain</span>
															<h4 style="color:silver;">Transfer from/to the Airport to/from  <em><strong>Zone 3</strong></em></h4>
											<hr>
											<h5 style="color:gray;">Executive Sedan</h5>
											<h6><strong>40.00 BD</strong></h6>
											<br>
											<h5 style="color:gray;">SUV</h5>
											<h6><strong>25.00 BD</strong></h6>
											<br>
											<h5 style="color:gray;">Standard Sedan</h5>
											<h6><strong>20.00 BD</strong></h6>
														</div>
										<hr>
										<span style="color:rgba(0,125,160,1.00);">Covers Hamad Town, Zallaq, BIC, King Fahad Causeway, Durrat Al Bahrain	</span>
													</div>
													</div>
												</div>
											</div>
										</div>


									</div>
								</div>



						 <div class="more-info about-info" style="margin-top:50px;">
								<div class="container">
									<div class="row">
								<div class="col-md-12">
											<div class="section-heading" style="border:opx solid black;margin-bottom:50px;text-align:left;">
												<h4>Hourly Chauffeured Service <em></em></h4>
												<span></span>
											</div>
										</div>

										<div class="col-md-3 box" style="background-color:;border:2px solid silver;">
											<div class="more-info-content">
												<div class="row">
													<div class="col-md-12 align-self-center" style="border:0px solid silver;padding:25px;">
														<div class="right-content">
															<span>Chauffeured Service</span>
															<h4 style="color:silver;"> <em>Standard Sedan</em></h4>
											<hr>
											<h5 style="color:gray;">Per Hour</h5>
											<h6><strong>12.00 BD</strong></h6>
												<h6>(Minimum 3 hours)</h6>
											<br>
											<h5 style="color:gray;">Per Day/8 Hours</h5>
											<h6><strong>80.00 BD</strong></h6>
											<br>
											<h5 style="color:gray;">Extra Hours</h5>
											<h6><strong>8.00 BD per hour</strong></h6>
														</div>

													</div>
												</div>
											</div>
										</div>

							 <div class="col-md-3 box" style="background-color:;border:2px solid silver;">
											<div class="more-info-content">
												<div class="row">
													<div class="col-md-12 align-self-center" style="border:0px solid silver;padding:25px;">
														<div class="right-content">
															<span>Chauffeured Service</span>
															<h4 style="color:silver;"> <em>Executive Sedan</em></h4>
											<hr>
											<h5 style="color:gray;">Per Hour</h5>
											<h6><strong>30.00 BD</strong></h6>
												<h6>(Minimum 3 hours)</h6>
											<br>
											<h5 style="color:gray;">Per Day/8 Hours</h5>
											<h6><strong>200.00 BD</strong></h6>
											<br>
											<h5 style="color:gray;">Extra Hours</h5>
											<h6><strong>20.00 BD per hour</strong></h6>
														</div>

													</div>
												</div>
											</div>
										</div>

								<div class="col-md-3 box" style="background-color:;border:2px solid silver;">
											<div class="more-info-content">
												<div class="row">
													<div class="col-md-12 align-self-center" style="border:0px solid silver;padding:25px;">
														<div class="right-content">
															<span>Chauffeured Service</span>
															<h4 style="color:silver;"> <em>SUV</em></h4>
											<hr>
											<h5 style="color:gray;">Per Hour</h5>
											<h6><strong>15.00 BD</strong></h6>
												<h6>(Minimum 3 hours)</h6>
											<br>
											<h5 style="color:gray;">Per Day/8 Hours</h5>
											<h6><strong>100.00 BD</strong></h6>
											<br>
											<h5 style="color:gray;">Extra Hours</h5>
											<h6><strong>10.00 BD per hour</strong></h6>
														</div>

													</div>
												</div>
											</div>
										</div>


							<div class="col-md-3 box" style="background-color:;border:2px solid silver;">
											<div class="more-info-content">
												<div class="row">
													<div class="col-md-12 align-self-center" style="border:0px solid silver;padding:25px;">
														<div class="right-content">
															<span>Chauffeured Service</span>
															<h4 style="color:silver;"> <em>Vans</em></h4>
											<hr>
											<h5 style="color:gray;">Per Hour</h5>
											<h6><strong>25.00 BD</strong></h6>
												<h6>(Minimum 3 hours)</h6>
											<br>
											<h5 style="color:gray;">Per Day/8 Hours</h5>
											<h6><strong>150.00 BD</strong></h6>
											<br>
											<h5 style="color:gray;">Extra Hours</h5>
											<h6><strong>15.00 BD per hour</strong></h6>
														</div>

													</div>
												</div>
											</div>
										</div>




									</div>
								</div>
							</div>




					</div>
				</div>
    </div>

</body>
{% endblock %}
</html>

abc_project/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>ABC LIMOUSINE</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
     <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
     <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
     <script src="https://cdn.jsdelivr.net/npm/popper.js@1.12.9/dist/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
     <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>

    <link rel="stylesheet" href="path/to/bootstrap/css/bootstrap.min.css">
    <link rel="stylesheet" href="path/to/font-awesome/css/font-awesome.min.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">


</head>
<body>
<div>
    {% include 'loader.html' %}
    {% include 'navbar.html' %}
    {% block content %}
    {% endblock %}
</div>
 {% include 'whatsapp.html' %}
 {% include 'footer.html' %}

</body>
</html>

abc_project/templates/contact.html
{% extends 'base.html' %}
{% load static %}


<!DOCTYPE html>
<html lang="en" xmlns="http://www.w3.org/1999/html">
<head>
    <meta charset="UTF-8">
    {% block title %}
    Contact
    {% endblock %}
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">



</head>
{% block content %}
<body>


<div class="with-sidebar-wrapper py-5 mt-5">
				<div class="with-sidebar-container container">
					<div class="with-sidebar-left eight columns">
						<div class="with-sidebar-content twelve columns">
							<section id="content-section-2"><div class="section-container container"><div class="limoking-item limoking-about-us-item limoking-with-divider" style="margin-bottom: 60px;"><div class="about-us-title-wrapper"><h3 class="about-us-title">CONTACT US</h3><div class="about-us-title-divider"></div></div><div class="about-us-content-wrapper"><div class="about-us-content limoking-skin-content"><p>Feel free to contact us for booking&nbsp; one of the best limousine taxi services in Bahrain</p>
</div></div><div class="clear"></div></div><div class="clear"></div><div class="clear"></div><div class="limoking-item limoking-content-item" style="margin-bottom: 60px;"><p><span class="clear"></span><span class="limoking-space" style="margin-top: -22px; display: block;"></span>
</p><h5 class="limoking-heading-shortcode " style="font-weight: bold;">Please fill the form below. </h5>
<p> <span class="clear"></span><span class="limoking-space" style="margin-top: 25px; display: block;"></span> </p><div role="form" class="wpcf7" id="wpcf7-f5-o1" lang="en-US" dir="ltr">
<div class="screen-reader-response"></div>
<form action="/contact-us/#wpcf7-f5-o1" method="post" class="wpcf7-form" novalidate="novalidate">
<div style="display: none;">
<input type="hidden" name="_wpcf7" value="5">
<input type="hidden" name="_wpcf7_version" value="4.5.1">
<input type="hidden" name="_wpcf7_locale" value="en_US">
<input type="hidden" name="_wpcf7_unit_tag" value="wpcf7-f5-o1">
<input type="hidden" name="_wpnonce" value="3ed4a06f65">
</div>
<p><label> Your Name (required)<br>
    <span class="wpcf7-form-control-wrap your-name"><input type="text" name="your-name" value="" size="40" class="wpcf7-form-control wpcf7-text wpcf7-validates-as-required" aria-required="true" aria-invalid="false"></span> </label></p>
<p><label> Your Email (required)<br>
    <span class="wpcf7-form-control-wrap your-email"><input type="email" name="your-email" value="" size="40" class="wpcf7-form-control wpcf7-text wpcf7-email wpcf7-validates-as-required wpcf7-validates-as-email" aria-required="true" aria-invalid="false"></span> </label></p>
<p><label> Subject<br>
    <span class="wpcf7-form-control-wrap your-subject"><input type="text" name="your-subject" value="" size="40" class="wpcf7-form-control wpcf7-text" aria-invalid="false"></span> </label></p>
<p><label> Your Message<br>
    <span class="wpcf7-form-control-wrap your-message"><textarea name="your-message" cols="40" rows="10" class="wpcf7-form-control wpcf7-textarea" aria-invalid="false"></textarea></span> </label></p>
<p><input type="submit" value="Send" class="wpcf7-form-control wpcf7-submit"><img class="ajax-loader" src="http://www.abclimousinebh.com/wp-content/plugins/contact-form-7/images/ajax-loader.gif" alt="Sending ..." style="visibility: hidden; opacity: 1;"></p>
<div class="wpcf7-response-output wpcf7-display-none"></div></form></div><p></p>
</div><div class="clear"></div></div></section>
						</div>

						<div class="clear"></div>
					</div>

<div class="limoking-sidebar limoking-right-sidebar four columns">
	<div class="limoking-item-start-content sidebar-right-item">

		</div>
    <div id="text-7" class="widget widget_text limoking-item limoking-widget"><h3 class="limoking-widget-title">Contact Information</h3><div class="clear"></div>			<div class="textwidget"><p>Al Faisal Car Rental<br>
Block 405, Road 81, Building 384,<br>
Manama,<br>
Kingdom of Bahrain</p>
<p><i class="limoking-icon fa fa-envelope" style="vertical-align: middle; color: #444444; font-size: 16px; "><a href="mailto:info@abclimousinebh.com"></i>info@abclimousinebh.com</p></a>
<p><i class="limoking-icon fa fa-phone" style="vertical-align: middle; color: #444444; font-size: 16px; "><a href="tel:1234567"></i> 1234567</p></a>
</div>
		</div><div id="text-8" class="widget widget_text limoking-item limoking-widget"><h3 class="limoking-widget-title">Social Media</h3><div class="clear"></div>			<div class="textwidget"><a href="http://facebook.com/goodlayers"><i class="limoking-icon fa fa-facebook" style="vertical-align: middle; color: #444444; font-size: 28px; "></i></a> <a href="http://twitter.com/goodlayers"><i class="limoking-icon fa fa-twitter" style="vertical-align: middle; color: #444444; font-size: 28px; "></i></a> <a href="#"><i class="limoking-icon fa fa-dribbble" style="vertical-align: middle; color: #444444; font-size: 28px; "></i></a> <a href="#"><i class="limoking-icon fa fa-pinterest" style="vertical-align: middle; color: #444444; font-size: 28px; "></i></a> <a href="#"><i class="limoking-icon fa fa-google-plus" style="vertical-align: middle; color: #444444; font-size: 28px; "></i></a> <a href="#"><i class="limoking-icon fa fa-instagram" style="vertical-align: middle; color: #444444; font-size: 28px; "></i></a></div>
		</div>	</div>
</div>
					<div class="clear"></div>
				</div>
			</div>

<div class="container">
    <div id="m" style="height: 403px; width: 102%;"></div>
       <script>
           function initMap() {
           var loc = {lat: -26.334, lng: 132.034};
           var m1 = new google.maps.Map(
           document.getElementById('m'), {zoom: 3, center: loc});
           var mar = new google.maps.Marker({position: loc, map: m1});
           }
        </script>
       <script async defer src="https://maps.googleapis.com/maps/api/js?key=YOUR_API_KEY&callback=initMap"></script>
</div>


</body>
{% endblock %}
</html>

abc_project/templates/home.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <title>ABC Limousine</title>
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
     <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/css/bootstrap.min.css"  crossorigin="anonymous">
     <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js"  crossorigin="anonymous"></script>
     <script src="https://cdn.jsdelivr.net/npm/popper.js@1.12.9/dist/umd/popper.min.js"  crossorigin="anonymous"></script>
     <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/js/bootstrap.min.js"  crossorigin="anonymous"></script>
</head>
<body>
<div style="position:fixed; width:100%">
    <a href="{% url 'limousineapp:index'  %}">
        <video width="100%" height="100%" autoplay loop muted>
            <source src="{% static 'images/video1.mp4' %}" type="video/mp4">
         </video>
     </a>
</div>




</body>
</html>

abc_project/templates/loader.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
<style>
/* Center the loader */
#loader {
  position: absolute;
  left: 50%;
  top: 50%;
  z-index: 1;
  width: 120px;
  height: 120px;
  margin: -76px 0 0 -76px;
  border: 16px solid #f3f3f3;
  border-radius: 50%;
  border-top: 16px solid #3498db;
  -webkit-animation: spin 2s linear infinite;
  animation: spin 2s linear infinite;
}

@-webkit-keyframes spin {
  0% { -webkit-transform: rotate(0deg); }
  100% { -webkit-transform: rotate(360deg); }
}

@keyframes spin {
  0% { transform: rotate(0deg); }
  100% { transform: rotate(360deg); }
}

/* Add animation to "page content" */
.animate-bottom {
  position: relative;
  -webkit-animation-name: animatebottom;
  -webkit-animation-duration: 1s;
  animation-name: animatebottom;
  animation-duration: 1s
}

@-webkit-keyframes animatebottom {
  from { bottom:-100px; opacity:0 }
  to { bottom:0px; opacity:1 }
}

@keyframes animatebottom {
  from{ bottom:-100px; opacity:0 }
  to{ bottom:0; opacity:1 }
}

#myDiv {
  display: none;
  text-align: center;
}
</style>
</head>
<body onload="myFunction()" style="margin:0;">

<div id="loader"></div>

<div style="display:none;" id="myDiv" class="animate-bottom">
<!--  <h2>Tada!</h2>-->
<!--  <p>Some text in my newly loaded page..</p>-->
</div>

<script>
var myVar;

function myFunction() {
  myVar = setTimeout(showPage, 3000);
}

function showPage() {
  document.getElementById("loader").style.display = "none";
  document.getElementById("myDiv").style.display = "block";
}
</script>

</body>
</html>

abc_project/templates/navbar.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<nav class="navbar fixed-top shadow-sm navbar-expand-lg bg-dark navbar-dark px-lg-5 py-3">
        <a href="index.html" class="navbar-brand d-block d-lg-none">
            <h1 class="font-secondary text-white mb-n2">ABC <span class="text-primary">LIMOUSINE</span>SERVICE</h1>
        </a>
        <button type="button" class="navbar-toggler" data-toggle="collapse" data-target="#navbarCollapse">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse justify-content-between" id="navbarCollapse">
            <div class="navbar-nav ml-auto py-0">
                <a href="{% url 'limousineapp:index' %}" class="nav-item nav-link active">HOME</a>
                <a href="{% url 'limousineapp:about' %}" class="nav-item nav-link">ABOUT</a>
            <div class="dropdown">
                <button class="btn btn-dark dropdown-toggle" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                   RATES
                 </button>
                    <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
                    <a class="dropdown-item" href="{% url 'limousineapp:bahrain' %}">BAHRAIN</a>
                    <a class="dropdown-item" href="{% url 'limousineapp:saudi' %}">SAUDI ARABIA</a>
                       </div>
             </div>

            </div>
            <a href="index.html" class="navbar-brand mx-5 d-none d-lg-block col">
                <h1 class="font-secondary text-white mb-n2">ABC <span class="text-primary">LIMOUSINE</span> SERVICE</h1>
            </a>
            <div class="navbar-nav mr-auto py-0">
                <a href="{% url 'limousineapp:gallery' %}" class="nav-item nav-link">GALLERY</a>
                <a href="{% url 'limousineapp:review' %}" class="nav-item nav-link">REVIEWS</a>
                <a href="{% url 'limousineapp:contact' %}" class="nav-item nav-link">CONTACT</a>
            </div>
        </div>
    </nav>

</body>
</html>

abc_project/templates/whatsapp.html
{% load static %}

<style>
.whatsapp_float{
    position:fixed;
    bottom:100px;
    right:20px;
}

</style>
<div class="whatsapp_float">
    <a href="https://wa.me/+918547884465/?text=urlencodedtext" target="_blank"><img src="{% static 'images/whatsapp.png' %}" width="70px" class="whatsapp_float_btn"></a>

</div>